name: Coverage

on:
  push:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn coverage
    - uses: codecov/codecov-action@v2
      with:
        directory: coverage
