name: Coverage

on:
  push:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - uses: actions/checkout@v3
    - run: yarn install
    - run: yarn coverage
    - uses: codecov/codecov-action@v3
      with:
        directory: coverage
